import ScriptManager from "./ScriptManager.js";

const manager = new ScriptManager(["audio"], ["sample"]);

manager.center("Trong lớp");
manager.center("Hành lang");
manager.center("Dưới sân");

manager.scenes([
  { sampleVideo: [manager.sampleVideos.sample, "0:00 - 0:12"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:13 - 0:22"], actors: ["Tất cả"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:29 - 0:35.3"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:36 - 0:37.4"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:37.8 - 0:38.25"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:38.5 - 0:39.5"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:39.8 - 0:41.4"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:42 - 0:45.3"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:45.5 - 0:47"], actors: ["Tất cả"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:47.3 - 0:50"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:50.5 - 0:53.1"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:53.3 - 0:56.5"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:56.8 - 0:58.3"], actors: ["5-6 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "0:58.6 - 1:00.4"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:00.8 - 1:02.6"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:02.8 - 1:04.5"], actors: ["6-7 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:04.7 - 1:07.7"], actors: ["1 người", "tất cả"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:08 - 1:10.2"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:10.4 - 1:12"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:12.3 - 1:13.8"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:14 - 1:15.8"], actors: ["5 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:16 - 1:17.7"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:18 - 1:19.8"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:19.8 - 1:23.4"], actors: ["8 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:23.7 - 1:27.3"], actors: ["4 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:27.55 - 1:29.8"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:30.1 - 1:34.3"], actors: ["6 người"] },
  { audio: [manager.audios.audio, "1:42.7 - 1:46.2"], description: "1 người đứng giữa, 4 người đứng xung quanh, lần lượt chạy tới ôm người giữa theo nhạc", actors: ["5 người"] },
  { audio: [manager.audios.audio, "1:46.5 - 1:48.8"], description: "Nhảy loạn xạ như bị \"điên\"", actors: ["4-5 người"] },
  { audio: [manager.audios.audio, "1:49 - 1:50.5"], description: "Ôm không khí, xoay vòng tròn", actors: ["1 người"] },
  { audio: [manager.audios.audio, "1:50.7 - 1:52.5"], description: "Ghi dang dở bài thơ lên bảng", actors: ["1 người"] },
  { audio: [manager.audios.audio, "1:52.7 - 1:53.8"], description: "1 người lấy tay quơ lên đầu người kia (edit gắn nametag trong Minecraft)", actors: ["2 người"] },
  { audio: [manager.audios.audio, "1:54 - 1:57.6"], description: "1 người nhìn thấy người kia và chạy tới ôm, chuyển cảnh thành ôm cái cây", actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:34.38 - 1:38.5"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:38.67 - 1:45.5"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:45.9 - 1:50.1"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:50.35 - 1:54"], actors: ["5-6 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:54.3 - 1:57.5"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "1:57.8 - 2:01"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:01.9 - 2:03"], actors: ["6 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:03.3 - 2:05.5"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:05.8 - 2:06.5"], actors: ["1 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:06.8 - 2:09.4"], actors: ["4 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:09.55 - 2:12.5"], actors: ["Tất cả"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:12.8 - 2:14"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:14.4 - 2:16"], actors: ["6-7 người"] },
  { audio: [manager.audios.audio, "2:40 - 2:47"], description: "5 người xếp tay thành hình ngôi sao, 1 người ngồi nói chuyện với ngôi sao", actors: ["6 người"] },
  { audio: [manager.audios.audio, "2:47.2 - 2:51"], description: "1 người đi ngang, 4-5 đứng uốn éo", actors: ["5-6 người"] },
  { audio: [manager.audios.audio, "2:51.3 - 2:53.1"], description: "Chỉ 2 ngón trỏ vào nhau (ngại ngùng)", actors: ["1 người"] },
  { audio: [manager.audios.audio, "2:53.1 - 2:54.9"], description: "1 người đang ăn (cái gì đó), thấy người kia đi ngang qua thì nhìn rơi cả đũa", actors: ["2 người"] },
  { audio: [manager.audios.audio, "2:55.1 - 2:58.3"], description: "1 người ngồi trong lớp (gần cửa sổ), người kia thò tay vào để nắm tay, người trong lớp đập tay người bên ngoài, người bên ngoài quắn quéo", actors: ["2 người"] },
  { audio: [manager.audios.audio, "2:58.7 - 3:02.6"], description: "Đập bàn đập ghế", actors: ["1-2 người"] },
  { audio: [manager.audios.audio, "3:02.8 - 3:06.4"], description: "Ngồi thở dài", actors: ["3-4 người"] },
  { audio: [manager.audios.audio, "3:06.6 - 3:09"], description: "Ngồi cười khờ", actors: ["1 người"] },
  { audio: [manager.audios.audio, "3:09.4 - 3:13.2"], description: "1 người đang đi thì bị người kia đẩy té xuống đè lên, 3 người khác chạy vào đè lên theo nhạc", actors: ["5 người"] },
  { audio: [manager.audios.audio, "3:13.4 - 3:17"], description: "Đang ở cảnh trên, người bị đè giơ tay lên cầu cứu, thêm 2 người khác nhảy vào đè tiếp", actors: ["Thêm 2 người"] },
  { audio: [manager.audios.audio, "3:17.2 - 3:19.4"], description: "Chạy nhảy tự do", actors: ["3 người"] },
  { audio: [manager.audios.audio, "3:19.6 - 3:21"], description: "Tự đi tự nói chuyện một mình", actors: ["1 người"] },
  { audio: [manager.audios.audio, "3:21.2 - 3:24.7"], description: "1 người đang vẽ vời trên đất thì bị người kia chạy tới xóa hết => đuổi đánh người kia", actors: ["2 người"] },
  { audio: [manager.audios.audio, "3:24.9 - 3:28.3"], description: "1 người đi lùi để né người kia vì người đó muốn ôm, người ở sau chạy tới ôm, thế là cả đám tiếp tục nhào lại ôm", actors: ["5-6 người"] },
  { audio: [manager.audios.audio, "3:28.5 - 3:32.5"], description: "Cả đám ngủ (đủ loại tư thế)", actors: ["Tất cả"] },
  { audio: [manager.audios.audio, "3:32.7 - 3:39.5"], description: "1 người trên lầu chống tay lên cằm nhìn đắm đuối người ở dưới lầu đang đi", actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:16.2 - 2:30.5"], actors: ["Tất cả"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:30.9 - 2:32.5"], actors: ["2 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:32.7 - 2:35"], actors: ["3 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:35.2 - 2:36.5"], actors: ["2 người"] },
  { audio: [manager.audios.audio, "4:02 - 4:09"], description: "Mọi người xếp hàng ngang, máy quay lần lượt quay từng người (biểu cảm tùy ý)", actors: ["7-8 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:45.5 - 2:49.5"], actors: ["8 người"] },
  { audio: [manager.audios.audio, "4:13.7 - 4:17.5"], description: "Đang ở cảnh trên, 4 cặp xoay vòng tròn", actors: [""] },
  { audio: [manager.audios.audio, "4:17.5 - 4:20"], description: "Ôm đầu chạy nhảy", actors: ["3-4 người"] },
  { audio: [manager.audios.audio, "4:20.2 - 4:21.5"], description: "Đi xe một mình nhưng nói chuyện với người phía sau", actors: ["1 người"] },
  { audio: [manager.audios.audio, "4:21.7 - 4:25"], description: "2 người kéo, tranh giành 1 người", actors: ["3 người"] },
  { audio: [manager.audios.audio, "4:25.2 - 4:28.8"], description: "Cả đám dí theo một người để ôm (4 cảnh khác nhau)", actors: ["6-7 người"] },
  { sampleVideo: [manager.sampleVideos.sample, "2:49.9 - 3:03.3"], actors: ["Tất cả"] },
]);
